version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: coffee
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: coffeeS
      dockerfile: Dockerfile
      args:
        - APP_PORT=8080
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: coffee
      DB_USER: admin
      DB_PASSWORD: 1234

  lb:
    build:
      context: loadBalancer
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - app
    ports:
      - "8088:8088"
    environment:
      IP_LIST: 8080

volumes:
  postgres_data:
